# Generated by Django 4.2.17 on 2025-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
